### ISSUE TITLE
Not working on heroku

### ISSUE THREAD

**Issue by kalyandechiraju** [Aufree/bootstrap-material-design#11]
Installed the gem as in the documentation. It's working perfectly fine locally, but when uploaded to Heroku, old normal bootstrap is being loaded.

**Comment by Aufree** [comment]
You can try to run `heroku run rake assets:precompile`

**Comment by kalyandechiraju** [comment]
Tried it. Still the same. Not working.
My production.rb has 
config.serve_static_files = true
config.assets.compile = true
config.assets.digest = true
config.assets.js_compressor = :uglifier

**Comment by Aufree** [comment]
Try to do something below [this folder](https://github.com/Aufree/bootstrap-material-design/tree/master/test/dummy_app), That's a dummy app of this gem, I think it should be able to works.

**Comment by Aufree** [comment]
If my suggestion is work for you, please let me know all about that, so I can close this issue.

**Comment by kalyandechiraju** [comment]
I don't know what I am missing. But I will slowly figure it out from your demo project. Thank you. I will close the issue.
