### ISSUE TITLE
Input form-control animation broken

### ISSUE THREAD

**Issue by joaolfb** [Aufree/bootstrap-material-design#13]
The Css file that handles the input box animation does not work because there is an error in the transition statement.

Around line 4883 and 4893  on material.css.erb
select[multiple].form-control,
select[multiple].form-control:focus,
select[multiple].form-control.focus {
  height: 85px;
--  transition: background 0 ease-out;
++  transition: background 0s ease-out;
}

Tested on google Chrome and works with this litle change.

**Comment by carsonwright** [comment]
This is true, why has this not been merged?

**Comment by carsonwright** [comment]
@joaolfb Do you have a fork with this working?

**Comment by Aufree** [comment]
Thanks for your feed back, You can update your gem to version 0.2.2, It should works now.

**Comment by carsonwright** [comment]
Good job @Aufree thanks for the fix
