### ISSUE TITLE
Cant load fonts for icons

### ISSUE THREAD

**Issue by dreadstar** [Aufree/bootstrap-material-design#6]
hello,
I want to use this gem but keep getting an error message that the fonts cant be found:
http://[server]/assets/fonts/Material-Design-Icons.woff?-g7cqhn 
http://[server]/assets/fonts/Material-Design-Icons.woff?-g7cqhn 

the errors are coming from material-wsfont.css.

i am running Rails 4. The only divergence form the install instructions is that i placed:
/*
 *= require bootstrap-material-design
 *
 */
in base.css instead of application.cs.scss.
the application.css.scss contains:
@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootstrap/theme";

the manifests generate the following html:
<link href="/assets/application.css?body=1" media="screen" rel="stylesheet" />
	 <link href="/assets/custom.css?body=1" media="screen" rel="stylesheet" />
	 <link href="/assets/bootstrap-material-design/material.css?body=1" media="screen" rel="stylesheet" />
<link href="/assets/bootstrap-material-design/ripples.css?body=1" media="screen" rel="stylesheet" />
<link href="/assets/bootstrap-material-design/snackbar.css?body=1" media="screen" rel="stylesheet" />
<link href="/assets/bootstrap-material-design/material-wfont.css?body=1" media="screen" rel="stylesheet" />
<link href="/assets/bootstrap-material-design/index.css?body=1" media="screen" rel="stylesheet" />
<link href="/assets/base.css?body=1" media="screen" rel="stylesheet" />

And my Gemfile has:
sing rake 10.3.2
Using i18n 0.6.11
Using json 1.8.1
Using minitest 5.4.3
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.1.4
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.4
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.1.4
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 4.1.4
Using activemodel 4.1.4
Using active_model_serializers 0.9.0
Using arel 5.0.1.20140414130214
Using activerecord 4.1.4
Using bundler 1.8.2
Using thor 0.19.1
Using railties 4.1.4
Using hike 1.2.3
Using multi_json 1.10.1
Using tilt 1.4.1
Using sprockets 2.11.3
Using sprockets-rails 2.2.0
Using rails 4.1.4
Using angular_rails_csrf 1.0.3
Using angularjs-rails 1.3.10
Using execjs 2.2.2
Using autoprefixer-rails 5.1.6
Using bcrypt 3.1.9
Using sass 3.2.19
Using bootstrap-sass 3.3.3
Using bootstrap-material-design 0.1.5
Using bower 0.0.2
Using bower-rails 0.9.2
Using browserify-rails 0.5.1
Using coffee-script-source 1.8.0
Using coffee-script 2.3.0
Using coffee-rails 4.0.1
Using orm_adapter 0.5.0
Using responders 1.1.2
Using warden 1.2.3
Using devise 3.4.1
Using dotenv-deployment 0.0.2
Using dotenv 0.11.1
Using foreman 0.75.0
Using geocoder 1.2.7
Using haml 4.0.5
Using haml-rails 0.5.3
Using jbuilder 2.2.5
Using jquery-rails 3.1.2
Using lodash-rails 2.4.1
Installing material_design_icons_rails 1.0.0
Using mini_portile 0.6.2
Using mysql2 0.3.17
Using nokogiri 1.6.6.2
Using nokogumbo 1.3.0
Using pg 0.18.1
Using polymer-rails 0.2.8
Using polymer-core-rails 0.2.5
Using polymer-paper-rails 0.2.5
Using rails-assets-angular 1.3.14
Using rails-assets-angular-devise 1.0.2
Using rails_serve_static_assets 0.0.4
Using rails_stdout_logging 0.0.3
Using rails_12factor 0.0.3
Using rdoc 4.1.2
Using realtime 0.0.12
Using redis 3.1.0
Using sass-rails 4.0.4
Using sdoc 0.4.1
Using spring 1.1.3
Using turbolinks 2.5.2
Using uglifier 2.5.3
Using yaml_db 0.3.0
Ruby 2.0.0

and bower has:
├── angular#1.3.14 (1.4.0-build.3859+sha.bfd7b22 available)
├─┬ angular-animate#1.3.14 (1.4.0-build.3859+sha.bfd7b22 available)
│ └── angular#1.3.14 (latest is 1.4.0-build.3859+sha.bfd7b22)
├─┬ angular-material#0.8.1
│ ├── angular#1.3.14 (1.3.15-build.59+sha.75abbd5 available, latest is 1.4.0-build.3859+sha.bfd7b22)
│ ├── angular-animate#1.3.14 (1.3.15-build.59+sha.75abbd5 available, latest is 1.4.0-build.3859+sha.bfd7b22)
│ └─┬ angular-aria#1.3.14 (1.3.15-build.59+sha.75abbd5 available, latest is 1.4.0-build.3859+sha.bfd7b22)
│   └── angular#1.3.14
├─┬ angular-socket-io#0.7.0
│ └── angular#1.3.14 (1.4.0-build.3859+sha.bfd7b22 available)
├── animate.css#3.2.1

I also tried to install the material-design-icons for rails asset pipeline, to no avail and adding the fonts to the precompiled assets via assets.rb.

Any guidance would be greatly appreciated.

Thanks,
Tyrone

**Comment by Aufree** [comment]
That was a bug, you need to update `bootstrap-material-design`, then restart your server, also you can clone my gem in your computer, then run `cd bootstrap-material-design/test/dummy_app  && bundle && rails s`, just give a demo for you.

**Comment by dreadstar** [comment]
Thanks so much for the quick response.  that fixed those error messages.
