### ISSUE TITLE
error when deploying on heroku

### ISSUE THREAD

**Issue by dreadstar** [Aufree/bootstrap-material-design#7]
I get the following message when i try to do  a git push heroku master:

remote:        rake aborted!
remote:        ExecJS::RuntimeError: CssSyntaxError: /tmp/build_48c7454a414e5504a72c161ab263da2f/vendor/bundle/ruby/2.0.0/gems/bootstrap-material-design-0.1.6/app/assets/stylesheets/bootstrap-material-design/material.css.map:1:14: Unknown word

there is a actually a lot more that prints out but this seemed to be the core of the error msg.

Thanks,
T

**Comment by Aufree** [comment]
Thanks for your feedback, I just remove those *.css.map file, you need to update your gem again, and try to push your application to heroku.

**Comment by dreadstar** [comment]
That resolved it :) Thanks you again for such a quick response :) Have great weekend!

**Comment by Aufree** [comment]
You're welcome.
